# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres"
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=faredb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  tripfare_service:
    image: tripfare:latest
    container_name: tripfare
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - database