spring:
  application:
    name:tripfare
  datasource:
    url: jdbc:postgresql://localhost:5432/faredb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    liquibase: enabled
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    hibernate:
      ddl-auto: update

